const KEY='bernice-europe-compare-v2';
let saved;try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{saved={}}
saved={favorites:Array.isArray(saved.favorites)?saved.favorites:[],notes:saved.notes||{},compare:Array.isArray(saved.compare)?saved.compare:[]};
let region='all',view='all',sort='price',lastTrigger=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fmt=n=>'NT$'+new Intl.NumberFormat('zh-TW',{maximumFractionDigits:0}).format(n);
const persist=()=>localStorage.setItem(KEY,JSON.stringify(saved));
const color=s=>s==='green'?'var(--green)':s==='yellow'?'var(--yellow)':'var(--gray)';

function gallery(t){const label=t.priority?'主候選':t.statusText;return `<div class="gallery ${t.photos.length===1?'one':''}">${t.photos.slice(0,3).map((p,i)=>`<img src="${p}" alt="${t.name}代表照片${i+1}" loading="lazy" onerror="this.style.visibility='hidden'">`).join('')}<span class="agency">${t.agency}</span><span class="rec ${t.priority?'main-candidate':''}">${label}</span><span class="caption">${t.photoCaption}</span></div>`}
function card(t){const fav=saved.favorites.includes(t.id),checked=saved.compare.includes(t.id);return `<article class="trip">${gallery(t)}<div class="trip-body"><div class="identity"><div><h2>${t.name}</h2><div class="formal">${t.formal}</div></div><div class="price">${t.priceLabel}<small>／人</small></div></div><div class="facts"><div class="fact"><small>旅遊天數</small><b>${t.days}天</b></div><div class="fact"><small>航空公司</small><b>${t.airline}</b></div><div class="fact"><small>轉機</small><b>${t.transfer}</b></div></div><div class="tags">${t.tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div class="callout feature"><b>✨ 最大特色</b><p>${t.feature}</p></div><div class="callout analysis"><b>💬 我的分析</b><p>${t.analysis}</p></div><div class="actions"><button class="btn ${fav?'faved':''}" data-fav="${t.id}">${fav?'♥ 已喜歡':'♡ 喜歡'}</button><button class="btn ${checked?'checked':''}" data-compare="${t.id}">${checked?'✓ 已選比較':'＋ 加入比較'}</button><button class="btn primary" data-detail="${t.id}">查看詳情</button></div></div></article>`}
function render(){let list=TOURS.filter(t=>t.priority);if(region!=='all')list=list.filter(t=>t.region===region);if(view==='fav')list=list.filter(t=>saved.favorites.includes(t.id));if(sort==='price')list.sort((a,b)=>a.price-b.price);if(sort==='days')list.sort((a,b)=>a.days-b.days||a.price-b.price);$('#cards').innerHTML=list.length?list.map(card).join(''):'<div class="empty">這個條件目前沒有行程。</div>';$('#count').textContent=`${list.length}團`;const low=list.length?Math.min(...list.map(x=>x.price)):0;$('#lowest').textContent=low?fmt(low):'—';$('#archive').innerHTML=TOURS.filter(t=>!t.priority).map(t=>`<div class="archive-item"><div><strong>${t.agency}｜${t.name}</strong><small>${t.formal}｜${t.priceLabel}／人｜${t.availability}</small><small>${t.analysis}</small></div><div><button class="btn" data-detail="${t.id}">查看詳情</button> <button class="btn ${saved.compare.includes(t.id)?'checked':''}" data-compare="${t.id}">${saved.compare.includes(t.id)?'已選':'加入比較'}</button></div></div>`).join('');updateBar()}
function dates(t){return `<div class="date-list">${t.dates.map(x=>`<div class="date-row"><b>${x[0]}</b><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('')}</div>`}
function flights(t){return `<div class="flight-list">${t.flights.map(x=>`<div class="flight-row"><b>${x[0]}</b><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('')}</div>`}
function days(t){return `<div class="itinerary">${t.itinerary.map((x,i)=>{const photos=x.photos|| (x.photo?[{src:x.photo,caption:x.caption}]:[]);return `<details class="day-card" ${i===1?'open':''}><summary><span class="day-num">${x.title}</span><span class="route">${x.route}</span><span class="chev">⌄</span></summary><div class="day-content"><div class="day-tags">${x.tags.map(y=>`<span>${y}</span>`).join('')}</div><div class="day-layout ${photos.length?'has-photos':''}"><ol class="steps">${x.steps.map(y=>`<li>${y}</li>`).join('')}</ol>${photos.length?`<div class="day-photos" aria-label="${x.title} 已核實照片">${photos.map((p,n)=>`<figure class="day-photo"><img src="${p.src}" alt="${p.caption}" loading="lazy"><figcaption><b>${p.caption}</b><span>對應 ${x.title}・官方行程頁核實</span></figcaption></figure>`).join('')}</div>`:''}</div></div></details>`}).join('')}</div>`}
function deepAnalysis(t){const a=DEEP_ANALYSIS[t.id];if(!a)return'';return `<section class="box deep-analysis"><div class="analysis-title"><div><span>深入分析</span><h3>這團真正適不適合你？</h3></div><span class="analysis-badge">依已核實行程比較</span></div><p class="verdict">${a.verdict}</p><div class="analysis-grid"><article class="analysis-panel good"><h4>值得選的地方</h4><ul>${a.pros.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="analysis-panel caution"><h4>需要接受的代價</h4><ul>${a.cons.map(x=>`<li>${x}</li>`).join('')}</ul></article></div><div class="lens-grid"><article><small>行程節奏</small><p>${a.pace}</p></article><article><small>住宿與餐食</small><p>${a.stay}</p></article><article><small>適合什麼情況</small><p>${a.fit}</p></article><article class="compare-lens"><small>和其他候選相比</small><p>${a.compare}</p></article></div><p class="analysis-note">這是依目前官方行程、航班、住宿與季節資料做的判斷；天候、飯店與實際班次仍以旅行社行前通知為準。</p></section>`}
function detail(t,trigger){lastTrigger=trigger||document.activeElement;$('#detailTitle').textContent=`${t.agency}｜${t.name}`;const label=t.priority?'主候選':t.statusText;$('#detailContent').innerHTML=`<div class="detail-hero"><div class="box"><div class="candidate-line">${label}　${t.availability}</div><h3 style="font-size:1.28rem;margin-top:8px">${t.formal}</h3><p><b>✨ 最大特色</b><br>${t.feature}</p><p><b>💬 我的分析</b><br>${t.analysis}</p></div><div class="box"><div class="mini-grid"><div class="mini"><small>價格</small><b>${t.priceLabel}</b></div><div class="mini"><small>天數</small><b>${t.days}天</b></div><div class="mini"><small>適合程度</small><b>${t.comfort}</b></div></div><p><b>住宿節奏</b><br>${t.stays}</p><p><b>高海拔／體力</b><br>${t.altitude}</p><p><b>季節影響</b><br>${t.season}</p></div></div>${deepAnalysis(t)}<div class="box"><h3>🗓️ 可選出發日期</h3>${dates(t)}</div><div class="box"><h3>✈️ 完整航班</h3>${flights(t)}</div><div class="box"><h3>每日行程</h3><p class="formal">每天預設收起；點選後依序查看交通、景點、餐食、住宿與對應照片。只有旅行社提供時間時才顯示確切鐘點。</p>${days(t)}</div><div class="box"><h3>📝 私人筆記</h3><textarea class="notes" id="noteBox" placeholder="例如：喜歡這團的連泊；要詢問旅行社航班或房型……">${saved.notes[t.id]||''}</textarea><p class="formal">筆記只保存在目前這台裝置的瀏覽器。</p></div><div class="box"><h3>🔗 原始資料</h3><a class="source-link" href="${t.source}" target="_blank" rel="noopener">查看旅行社官方行程頁面 ↗</a><p class="formal">航班、飯店、價格與名額仍以旅行社最終行前資料為準；未核實內容均保留「待確認」。</p></div>`;openOverlay($('#detailOverlay'));setTimeout(()=>$('#noteBox')?.addEventListener('input',e=>{saved.notes[t.id]=e.target.value;persist()}),0)}
const topics=[['每人價格',t=>`${t.priceLabel}<br><small>${t.priceNote}</small>`],['天數與狀態',t=>`${t.days}天<br>${t.availability}`],['航空與轉機',t=>`${t.airline}<br>${t.transfer}`],['住宿節奏',t=>t.stays],['高海拔／體力',t=>t.altitude],['最大的特色',t=>t.feature],['季節影響',t=>t.season],['💬 我的分析',t=>t.analysis]];
function compare(){const list=saved.compare.map(id=>TOURS.find(t=>t.id===id)).filter(Boolean);$('#compareContent').innerHTML=`<div class="box"><p style="margin:0"><b>已選${list.length}團。</b>手機和iPad使用直向主題卡，不需要左右拖動超寬表格。</p></div><div class="compare-stack" style="--n:${list.length}">${topics.map(([name,get])=>`<section class="compare-topic"><h3>${name}</h3><div class="compare-items">${list.map(t=>`<div class="compare-item"><b>${t.name}</b>${get(t)}</div>`).join('')}</div></section>`).join('')}<section class="compare-topic"><h3>管理比較名單</h3><div class="compare-items">${list.map(t=>`<div class="compare-item"><b>${t.name}</b><button class="btn remove" data-remove="${t.id}">移出比較</button></div>`).join('')}</div></section></div>`;openOverlay($('#compareOverlay'))}
function openOverlay(el){el.classList.add('open');document.body.style.overflow='hidden';el.querySelector('.close').focus()}
function closeOverlay(el){el.classList.remove('open');if(!$$('.overlay.open').length)document.body.style.overflow='';lastTrigger?.focus?.()}
function updateBar(){saved.compare=saved.compare.filter(id=>TOURS.some(t=>t.id===id)).slice(0,4);const n=saved.compare.length;$('#compareBar').classList.toggle('show',n>0);$('#compareCount').textContent=`已選${n}團`;$('#openCompare').disabled=n<2;persist()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.region){region=b.dataset.region;$$('[data-region]').forEach(x=>x.classList.toggle('active',x===b));render();return}if(b?.dataset.view){view=b.dataset.view;$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render();return}if(b?.dataset.sort){sort=b.dataset.sort;$$('[data-sort]').forEach(x=>x.classList.toggle('active',x===b));render();return}if(b?.dataset.fav){const id=b.dataset.fav;saved.favorites=saved.favorites.includes(id)?saved.favorites.filter(x=>x!==id):[...saved.favorites,id];persist();render();return}if(b?.dataset.compare){const id=b.dataset.compare;if(saved.compare.includes(id))saved.compare=saved.compare.filter(x=>x!==id);else if(saved.compare.length<4)saved.compare.push(id);else alert('一次最多比較4團');persist();render();return}if(b?.dataset.detail){detail(TOURS.find(t=>t.id===b.dataset.detail),b);return}if(b?.dataset.remove){saved.compare=saved.compare.filter(x=>x!==b.dataset.remove);persist();compare();render();return}if(b?.hasAttribute('data-close')){closeOverlay(b.closest('.overlay'));return}if(b?.id==='openCompare'&&saved.compare.length>=2){lastTrigger=b;compare();return}if(e.target.classList.contains('overlay'))closeOverlay(e.target)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const open=$$('.overlay.open').pop();if(open)closeOverlay(open)}});
render();

function registerWebMCP(){const c=document.modelContext;if(!c?.registerTool)return;const reg=t=>{try{Promise.resolve(c.registerTool(t)).catch(()=>{})}catch{}};reg({name:'set_trip_favorite',title:'設定喜歡的行程',description:'將指定行程加入或移出喜歡清單。',inputSchema:{type:'object',properties:{tripId:{type:'string'},favorite:{type:'boolean'}},required:['tripId','favorite'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({tripId,favorite})=>{if(!TOURS.some(t=>t.id===tripId))throw Error('找不到行程');saved.favorites=saved.favorites.filter(x=>x!==tripId);if(favorite)saved.favorites.push(tripId);persist();render();return{tripId,favorite}}});reg({name:'save_trip_note',title:'儲存私人筆記',description:'在本機瀏覽器儲存指定行程筆記。',inputSchema:{type:'object',properties:{tripId:{type:'string'},note:{type:'string'}},required:['tripId','note'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:({tripId,note})=>{if(!TOURS.some(t=>t.id===tripId))throw Error('找不到行程');saved.notes[tripId]=String(note);persist();return{tripId,saved:true}}})}
registerWebMCP();
